version: '3.7'

networks:
  dummy-net:

services:

  ca-dummy:
    image: ${DOCKER_CA}
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-dummy
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b dummy-superadmin:X2334pw20 -d'
    volumes:
      - ${WORKDIR}/ca-repo/fabric-ca-server/dummy:/etc/hyperledger/fabric-ca-server
    container_name: ca-dummy
    networks:
      - dummy-net

  ca-dummy-orderer:
    image: ${DOCKER_CA}
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-dummy-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
    ports:
      - "9054:9054"
      - "19054:19054"
    command: sh -c 'fabric-ca-server start -b dummy-orderer-superadmin:X2003pw2x -d'
    volumes:
      - ${WORKDIR}/ca-repo/fabric-ca-server/orderer:/etc/hyperledger/fabric-ca-server
    container_name: ca-dummy-orderer
    networks:
      - dummy-net

  ca-tls:
    image: ${DOCKER_CA}
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-tls
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    ports:
      - "8054:8054"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b dummy-tls-superadmin:X2555pw4x -d'
    volumes:
      - ${WORKDIR}/ca-repo/fabric-ca-server/tlsca:/etc/hyperledger/fabric-ca-server
    container_name: ca-tls
    networks:
      - dummy-net