version: '3.7'

networks:
  dummy-net:

services:

  cli:
    container_name: cli
    image: ${DOCKER_TOOL}
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer/
    networks:
      - dummy-net
