
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer1.dummy.com"
    static_configs:
      - targets: ["orderer1.dummy.com:16050"]
  - job_name: "orderer2.dummy.com"
    static_configs:
      - targets: ["orderer2.dummy.com:16051"]
  - job_name: "orderer3.dummy.com"
    static_configs:
      - targets: ["orderer3.dummy.com:16052"]
  - job_name: "peer1.dummy.com"
    static_configs:
      - targets: ["peer1.dummy.com:6053"]
  - job_name: "peer2.dummy.com"
    static_configs:
      - targets: ["peer2.dummy.com:5053"]
  - job_name: "peer3.dummy.com"
    static_configs:
      - targets: ["peer3.dummy.com:4053"]
