# SPDX-License-Identifier: Apache-2.0
version: "2.1"

volumes:
  pgdata:
  walletstore:

networks:
  dummy-net:

services:
  explorerdb.dummy.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.dummy.com
    hostname: explorerdb.dummy.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${WORKDIR}/explorer/pgdata:/var/lib/postgresql/data
    networks:
      - dummy-net

  explorer.dummy.com:
    image: hyperledger/explorer:latest
    container_name: explorer.dummy.com
    hostname: explorer.dummy.com
    environment:
      - DATABASE_HOST=explorerdb.dummy.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ${WORKDIR}/explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ${WORKDIR}/explorer/conn-network.json:/opt/explorer/app/platform/fabric/conn-network.json
      - ${WORKDIR}/ca-repo:/tmp/crypto
      - ${WORKDIR}/explorer/walletstore:/opt/explorer/wallet
    ports:
      - 3071:8080
    depends_on:
      explorerdb.dummy.com:
        condition: service_healthy
    networks:
      - dummy-net
